### ISSUE TITLE
Module naming! Namespaces! Um…

### ISSUE THREAD

**Issue by iarna** [erkyrath/node-xml-zarf#1]
npm has support for namespaces, so you _could_ name this something like `@zarfeblong/xml`.

To do this you'd just edit your `package.json` to use a namespaced name and then the first time you publish run: `npm publish --access=public`. (Later publishes will remember that its public.)

Eh, not that it really matters, but every time I see a module with `node-` as a prefix or `-<username>` as a suffix my eyebrows twitch. =D

**Comment by erkyrath** [comment]
Sorry. :) I wrote it and used it long before I decided it was worth pushing to npmjs.
